#!/usr/bin/python

import argparse
import subprocess

# Parse command line arguments
parser = argparse.ArgumentParser(
    description='Execute a command until success, then execute a different command')
parser.add_argument('until_command', help='Command to execute until success')
parser.add_argument('finally_command', help='Command to execute upon success')
args = parser.parse_args()

print "I'll run this until it succeeds: \n%s" % args.until_command
print "Once it succeeds (exit code 0), I'll run: \n%s" % args.finally_command

working = False
times = 0
while working is not True:
    working = subprocess.call(args.until_command, shell=True) == 0
    times += 1
    print "I've run this command {0} times so far...".format(times)

subprocess.call(args.finally_command, shell=True)