#!/usr/bin/python

import sys
import time

try:
	timestamp = int(sys.argv[1]) / 1000000
	dt = time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime(timestamp))
	print dt
except IndexError:
	print "Usage: from_usec [microseconds]"