#!/usr/bin/env python
from datetime import datetime
import sys

try:
	print datetime.fromtimestamp(float(sys.argv[1])).strftime('%Y-%m-%d %H:%M:%S')
except IndexError:
	print "Usage: from_timestamp [timestamp]"
