#!/usr/bin/python

import subprocess
import sys
import pipes
import time

try:
    (process, host) = sys.argv[1:]
except ValueError:
    print "Usage: monitor [process] [host]"
    sys.exit()

output = 'Checking...'
while len(output) > 0:
    try:
        print output
        output = subprocess.check_output("clear; ssh {host} 'ps aux | grep {process} | grep -v grep'"\
            .format(process=process,host=host), shell=True)
        time.sleep(5)
    except subprocess.CalledProcessError:
        output = ''
    except KeyboardInterrupt:
        sys.exit()
    

while True:
    try:
        subprocess.call('say {process} is complete 2>/dev/null'.format(process=process), shell=True)
        time.sleep(15)
    except:
        sys.exit()
