#!/usr/bin/python

import sys
import time
import calendar

try:
	dt = sys.argv
	dt.pop(0)
	dt_str = " ".join(dt)
	timeobj = time.strptime(dt_str, "%Y-%m-%d %H:%M:%S")
	timestamp = int(calendar.timegm(timeobj) * 1000000)
	print timestamp
except ValueError:
	print "Usage: to_usec [%Y-%m-%d %H:%M:%S]"